feat: hiding scam transactions
DimensionDev/Maskbook pull request #11073
Opened 2023-11-02 09:48 UTC by beyond009

## Description

https://mask.atlassian.net/browse/MF-5236
Closes # (NO_ISSUE)

## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Previews

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

2023-11-03 01:41 UTC, guanbinrui commented on packages/mask/popups/pages/Wallet/components/ActivityList/index.tsx
> +                    !transaction.isScam || !hidingScamSettings.value ? (
Use `filter` before `map`.

2023-11-03 02:51 UTC, UncleBill commented on packages/mask/popups/pages/Wallet/WalletSettings/HidingScamTx.tsx
> +                <Icons.DangerOutline size={20} color={theme.palette.maskColor.second} />
```
                <Icons.DangerOutline size={20} color={theme.palette.maskColor.second} />
                                               ^^^^^
```

This color won't take effect unless you set color in the svg file to `currentColor`. You can learn from https://mask.atlassian.net/wiki/spaces/MASK/pages/314441730

2023-11-03 09:43 UTC, guanbinrui submitted a review, later dismissed

2023-11-03 09:46 UTC, UncleBill requested changes

2023-11-03 09:46 UTC, UncleBill commented on packages/mask/popups/pages/Wallet/components/ActivityList/index.tsx
> +                    .filter((transaction) => !hidingScamSettings.value || !transaction.isScam)
Filter result might be empty, do it in `useTransactions` instead.

2023-11-04 04:20 UTC, UncleBill submitted a review, later dismissed

2023-11-04 06:44 UTC, guanbinrui approved these changes

2023-11-04 06:47 UTC, guanbinrui approved these changes, later dismissed

2023-11-07 03:41 UTC, merged