chore: sync locale keys
DimensionDev/Maskbook pull request #1505
Opened 2020-09-01 12:10 UTC by septs

2020-09-01 12:48 UTC, guanbinrui approved these changes

2020-09-01 14:23 UTC, Jack-Works commented
plz rebase first

2020-09-01 15:09 UTC, septs commented
@Jack-Works rebase done.

2020-09-01 15:14 UTC, Jack-Works requested changes

2020-09-01 15:14 UTC, Jack-Works commented on src/_locales/ja/messages.json
> +    "plugin_file_service_display_name": "Plugin: File Service",
I think you should leave it empty then fallback to en string in the runtime so it can up to date with the en translation

2020-09-02 02:08 UTC, Jack-Works approved these changes

2020-09-02 02:08 UTC, merged