docs: add arch.md
DimensionDev/Maskbook pull request #2501
Opened 2021-02-26 07:43 UTC by Jack-Works

close #2417

2021-02-26 07:54 UTC, septs requested changes
move to docs folder

2021-03-01 10:02 UTC, septs approved these changes

2021-03-02 02:27 UTC, merged

2021-03-02 02:28 UTC, Jack-Works commented
hold on there is linter error @septs

2021-03-02 02:32 UTC, septs commented
ummmm