fix:  read stable coins list from a JSON file
DimensionDev/Maskbook pull request #2669
Opened 2021-03-26 06:54 UTC by lelenei

#2593

2021-03-26 13:43 UTC, Jack-Works submitted a review, later dismissed
@guanbinrui plz review

2021-03-26 13:47 UTC, guanbinrui requested changes

2021-03-26 13:47 UTC, guanbinrui commented on packages/maskbook/src/web3/hooks/useStableTokensDebank.ts
> +    return StableCoins.data.map((x: { id: string; decimals: number; name: string; symbol: string }) =>
The StableCoins can be a list of erc20records. Then you can use it directly.

2021-03-27 01:25 UTC, guanbinrui commented on packages/maskbook/src/web3/hooks/stables_coins.json
> +{
Do not copy & paste the response. Make it an array of `ERC20TokenDetailed` entities.

2021-03-29 05:48 UTC, Jack-Works approved these changes
LGTM on style

2021-03-29 06:58 UTC, guanbinrui commented on packages/maskbook/src/web3/hooks/stables_coins.json
> +        "active_user_count_24h": 99504,
Please remove below fields :

+ active_user_count_24h
+ total_supply
+ transfer_amount_24h
+ transfer_count_24h

2021-03-29 10:33 UTC, guanbinrui approved these changes

2021-03-29 14:07 UTC, Jack-Works approved these changes

2021-03-29 14:07 UTC, merged

2021-03-30 01:08 UTC, lelenei commented
close