fix: hide the expand button if nothing to view in expanded mode
DimensionDev/Maskbook pull request #2681
Opened 2021-03-28 12:24 UTC by lelenei

#2673

2021-03-28 14:17 UTC, Jack-Works commented
Need one approval from @guanbinrui or @zhouhanseng

2021-03-29 01:02 UTC, guanbinrui commented
> #2673

Hi @lelenei  Please take a view on this.

https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2021-03-29 01:09 UTC, guanbinrui requested changes

2021-03-29 01:09 UTC, guanbinrui commented on packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
> +            {detailedTokens.filter((x) =>
The token filtering logical was using twice. Please refactor it to only use once. A easy catch up solution is like:

```typescript
const visibleTokens = detailedTokens.filter(...)

// Then you can use visibleTokens directly, no need to filter detailedToken again.
```

2021-03-29 06:55 UTC, guanbinrui approved these changes

2021-03-29 06:56 UTC, merged