chore: remove Mask ITO
DimensionDev/Maskbook pull request #2777
Opened 2021-04-07 08:08 UTC by guanbinrui

2021-04-07 09:11 UTC, Jack-Works requested changes

2021-04-07 09:11 UTC, Jack-Works commented on packages/maskbook/src/plugins/ITO/types.ts
> -    is_mask?: boolean
since they're encoded into the payload, I think you should comment them out and we won't accidentally use them in the future in an incompatible way.

2021-04-08 10:36 UTC, Jack-Works submitted a review, later dismissed

2021-04-08 11:23 UTC, zhouhanseng approved these changes

2021-04-08 11:57 UTC, Jack-Works approved these changes

2021-04-08 11:57 UTC, merged