feat: labled current account in conllectible plugin
DimensionDev/Maskbook pull request #3009
Opened 2021-04-25 10:56 UTC by nuanyang233

closes #3001

2021-04-25 13:49 UTC, UncleBill approved these changes

2021-04-26 05:07 UTC, guanbinrui submitted a review, later dismissed

2021-04-26 05:17 UTC, Jack-Works submitted a review, later dismissed

2021-04-26 05:29 UTC, septs requested changes
plz resolve conflicts

2021-04-26 05:53 UTC, guanbinrui approved these changes

2021-04-26 05:55 UTC, septs submitted a review, later dismissed

2021-04-26 05:55 UTC, septs reviewed
plz re-sort i18n key order.

2021-04-26 06:00 UTC, septs approved these changes

2021-04-26 06:01 UTC, guanbinrui approved these changes

2021-04-26 06:05 UTC, merged