fix: cannot destructure property 'date' of 'bisect(...)' as it is und…
DimensionDev/Maskbook pull request #3688
Opened 2021-07-15 06:15 UTC by lelenei

…efined

closes #3479

2021-07-16 10:07 UTC, zhouhanseng commented on packages/maskbook/src/plugins/hooks/useLineChart.ts
> +            const v: { date: Date; value: number } | undefined = bisect(d3.mouse(this)[0])
keep DRY by declaring a function?

2021-07-20 04:08 UTC, Himself65 reviewed
remove the unused console.log by the way

```diff
Index: packages/maskbook/src/plugins/hooks/useLineChart.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/maskbook/src/plugins/hooks/useLineChart.ts b/packages/maskbook/src/plugins/hooks/useLineChart.ts
--- a/packages/maskbook/src/plugins/hooks/useLineChart.ts	(revision c9ff9c84a89b9b83150d01ff90853ed43f06db1e)
+++ b/packages/maskbook/src/plugins/hooks/useLineChart.ts	(date 1626753900374)
@@ -14,7 +14,6 @@
     const { top, right, bottom, left, width, height } = dimension
     const contentWidth = width - left - right
     const contentHeight = height - top - bottom
-    console.log(color)
     useEffect(() => {
         if (!svgRef.current) return
```

2021-07-20 04:12 UTC, Himself65 reviewed
There also has a bug which tooltip in the wrong place

![image](https://user-images.githubusercontent.com/14026360/126260741-03b420c6-3596-4b74-9e31-c61cd7190ffb.png)

2021-07-20 04:55 UTC, Himself65 requested changes
```diff
Index: packages/maskbook/src/plugins/hooks/useLineChart.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/maskbook/src/plugins/hooks/useLineChart.ts b/packages/maskbook/src/plugins/hooks/useLineChart.ts
--- a/packages/maskbook/src/plugins/hooks/useLineChart.ts	(revision c9ff9c84a89b9b83150d01ff90853ed43f06db1e)
+++ b/packages/maskbook/src/plugins/hooks/useLineChart.ts	(date 1626756882416)
@@ -14,7 +14,6 @@
     const { top, right, bottom, left, width, height } = dimension
     const contentWidth = width - left - right
     const contentHeight = height - top - bottom
-    console.log(color)
     useEffect(() => {
         if (!svgRef.current) return
 
@@ -120,16 +119,17 @@
         }
 
         // add tooltip
-        d3.select(svgRef.current).on('mousemove', function (event) {
+        d3.select(svgRef.current).on('mousemove', function () {
+            const mx = d3.mouse(this)[0]
+            if (mx > contentWidth) {
+                return
+            }
             const bisect = (mx: any) => {
                 const date = x.invert(mx)
                 const index = d3.bisector<{ date: Date; value: number }, Date>((d) => d.date).left(data, date, 1)
                 return data[index]
             }
-
-            const v: { date: Date; value: number } | undefined = bisect(d3.mouse(this)[0])
-            if (!v) return
-            const { date, value } = v
+            const { date, value } = bisect(mx)
 
             tooltip.attr('transform', `translate(${Number(x(date)) - 18},${y(value)})`).call(
                 callout,
```

this must be better, doesn't it?

2021-07-20 05:53 UTC, Himself65 submitted a review, later dismissed

2021-07-20 06:00 UTC, Himself65 approved these changes

2021-07-20 08:16 UTC, guanbinrui approved these changes

2021-07-20 08:16 UTC, merged