feat: MaskWebAuthn support
DimensionDev/Maskbook pull request #3795
Opened 2021-07-29 06:19 UTC by Himself65

closes #

2021-07-29 09:16 UTC, Himself65 commented
see the implementation third party(my blog), https://github.com/Himself65/himself65.github.io/tree/login-with-mask

2021-08-02 03:45 UTC, Jack-Works requested changes

2021-08-02 03:45 UTC, Jack-Works commented on packages/shared-base/src/Identifier/type.ts
> - * @internal symbol that used to construct this type from the Identifier
Don't remove this

2021-08-02 03:45 UTC, Jack-Works commented on packages/maskbook/src/modules/CryptoAlgorithm/interfaces/interface.ec.ts
> +    length?: 256,
Why make them optional?

2021-08-02 03:45 UTC, Jack-Works commented on packages/maskbook/src/database/webAuthn.ts
> +const db = createDBAccessWithAsyncUpgrade<WebAuthnDB, UpgradeKnowledge>(
Please use `createDBAccess` because you don't need an async upgrade.

2021-08-02 03:45 UTC, Jack-Works commented on packages/maskbook/src/database/webAuthn.ts
> +        openDB<WebAuthnDB>('masbook-webauthn-v1', currentTryOpen, {
```suggestion
        openDB<WebAuthnDB>('masbook-webauthn', currentTryOpen, {
```

2021-08-02 05:37 UTC, Himself65 commented on packages/shared-base/src/Identifier/type.ts
> - * @internal symbol that used to construct this type from the Identifier
mistake

2022-05-06 09:39 UTC, closed without merging