Fix/date not compatible on mobile
DimensionDev/Maskbook pull request #3971
Opened 2021-08-15 11:04 UTC by jk234ert

2021-08-15 15:25 UTC, Jack-Works requested changes
Do you really need `createAt` and `updateAt`? If not, we can remove those types.

2021-08-15 15:25 UTC, Jack-Works commented on packages/maskbook/src/utils/native-rpc/Web.ts
> +        updatedAt: p.updatedAt.valueOf(),
```suggestion
        createdAt: p.createdAt.getTime(),
        updatedAt: p.updatedAt.getTime(),
```

2021-08-15 15:25 UTC, Jack-Works commented on packages/maskbook/src/utils/native-rpc/Web.ts
> +        updatedAt: p.updatedAt.valueOf(),
```suggestion
        createdAt: p.createdAt.getTime(),
        updatedAt: p.updatedAt.getTime(),
```

2021-08-15 15:25 UTC, Jack-Works commented on packages/public-api/src/web.ts
> +    updatedAt: number // milliseconds since midnight, January 1, 1970 UTC.
```suggestion
    /** Unix timestamp */
    createdAt: number
    /** Unix timestamp */
    updatedAt: number
```

2021-08-15 15:25 UTC, Jack-Works commented on packages/public-api/src/web.ts
> +    updatedAt: number // milliseconds since midnight, January 1, 1970 UTC.
```suggestion
    /** Unix timestamp */
    createdAt: number
    /** Unix timestamp */
    updatedAt: number
```

2021-08-16 01:27 UTC, jk234ert commented
> Do you really need `createAt` and `updateAt`? If not, we can remove those types.

Yes apps need these props to sort the list, they are also necessary during backup & restore flow

2021-08-16 02:31 UTC, Jack-Works approved these changes

2021-08-16 02:32 UTC, merged