chore: not every PR has a related issue, remove the `closes #`
DimensionDev/Maskbook pull request #4057
Opened 2021-08-21 02:43 UTC by UncleBill

2021-08-23 06:50 UTC, UncleBill commented on .github/pull_request_template.md
> +<!-- Please refer to the related issue number with closes #<issue-d> -->
```suggestion
<!-- Please refer to the related issue with closes #<issue-d> -->
```

2021-08-23 06:50 UTC, UncleBill commented on .github/pull_request_template.md
> +<!-- Please refer to the related issue with closes #<issue-d> -->
```suggestion
<!-- Please refer to the related issue with closes #<issue-id> -->
```

2021-08-23 06:51 UTC, guanbinrui commented on .github/pull_request_template.md
> +<!-- Please refer to the related issue with closes #<issue-id> -->
```suggestion
<!-- Please refer to the related issue number -->
<!-- closes # -->
```

2021-08-23 07:02 UTC, UncleBill commented on .github/pull_request_template.md
> +<!-- Please refer to the related issue with closes #<issue-id> -->
changed `issue number` to `issue id`

2021-08-23 08:39 UTC, Jack-Works approved these changes

2021-08-24 06:16 UTC, Jack-Works commented
Actually I think it's ok to leave the `close #`

2021-09-07 14:44 UTC, septs requested changes
why?

2021-09-08 03:03 UTC, UncleBill commented
> why?

As the title says, not every PR has a related issue.

Well, I'm OK to it, and will close this.

2021-09-08 03:03 UTC, closed without merging