chore: add watchTwitterUserSettings
DimensionDev/Maskbook pull request #4321
Opened 2021-09-11 03:37 UTC by guanbinrui

<img width="1089" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/52657989/132934981-ff9a695e-b891-4a1e-b220-fcf3770b496c.png">
Part of  #4320

2021-09-11 03:39 UTC, guanbinrui commented on packages/injected-script/main/intrinsic.ts
> +    CustomEvent: no_xray_Event,
CC @Jack-Works I need to dispatch the event with data attached.

2021-09-13 01:19 UTC, Jack-Works requested changes
@guanbinrui Please don't edit injectedScript for this case. You can access Twitter's indexed db from then content script directly IMO.

2021-09-13 03:16 UTC, guanbinrui commented
> @guanbinrui Please don't edit injectedScript for this case. You can access Twitter's indexed db from then content script directly IMO.

Sure thing, will refactor it later.

2021-09-17 03:45 UTC, Jack-Works commented
And please notice, you must not open the indexed db before twitter creates it, otherwise twitter will break

2021-09-26 20:10 UTC, septs commented on packages/injected-script/main/settingsChange.ts
> +            open.onsuccess = function () {
```suggestion
            open.addEventListener('success', () => {
```

2021-12-27 02:46 UTC, closed without merging