Integrate Foundation NFT Marketplace
DimensionDev/Maskbook pull request #4540
Opened 2021-10-03 17:20 UTC by lucasespinosa28

I did this plugin for the hackathon, it was submitted but yet needs so fix in the UI, is now working.

![Screenshot from 2021-10-03 13-10-17](https://user-images.githubusercontent.com/52639395/135764596-5beb5d73-d84f-4b1c-bcb6-b5bb5dd4d87f.png)
https://gitcoin.co/issue/DimensionDev/Maskbook/4298/100026557

2021-10-06 07:33 UTC, guanbinrui commented on packages/maskbook/src/plugins/Foudation/utils.ts
> +    return `${address.slice(0, 6)}...${address.slice(-4)}`
Please search the `formatAddress` in the codebase.

2021-10-06 07:34 UTC, guanbinrui commented on packages/maskbook/src/plugins/Foudation/utils.ts
> +    const date = new Date(Number(unix) * 1000)
```suggestion
    const date = new Date(Number.parseInt(unix, 10) * 1000)
```

2021-10-06 07:36 UTC, guanbinrui commented on packages/maskbook/src/plugins/Foudation/types/index.ts
> +    tokenAddress?: any
Avoid `any` if possible.

2021-10-06 07:39 UTC, guanbinrui commented on packages/maskbook/src/plugins/Foudation/abis/Foundation.json
> +[
Move this file to `web3-contracts/abis`

2021-10-06 07:41 UTC, guanbinrui commented on packages/maskbook/src/plugins/Foudation/SNSAdaptor/FoundationPlaceBid.tsx
> +            ? '0xeB1bD095061bbDb1aD065524628812cae63e4222'
Move to `web3-constants`.

2021-10-06 07:41 UTC, guanbinrui commented on packages/maskbook/src/plugins/Foudation/SNSAdaptor/FoudationProvenances.tsx
> +                <>
The `key`  is lost.

2021-10-06 07:42 UTC, guanbinrui commented on packages/maskbook/src/plugins/Foudation/SNSAdaptor/FoudationProvenances.tsx
> +        if (a.date < b.date) {
`return b.date - a.date`

2021-10-06 07:43 UTC, guanbinrui commented on packages/maskbook/src/plugins/Foudation/SNSAdaptor/FoudationDescription.tsx
> +        <>
Remove the fragment element.

2021-10-06 07:43 UTC, guanbinrui commented on packages/maskbook/src/plugins/Foudation/SNSAdaptor/FoudationCountdown.tsx
> +            setInterval(timer, 1000)
Need to clean the timer.

2021-10-06 07:44 UTC, guanbinrui commented on packages/maskbook/src/plugins/Foudation/SNSAdaptor/FoudationCard.tsx
> +    useEffect(() => {
Try to use `useAsync`  or `useAsyncRetry` from `react-use`.

2021-10-06 07:45 UTC, guanbinrui commented on packages/maskbook/src/plugins/Foudation/Components.tsx
> +import { Box } from '@material-ui/core'
Remove this file if it's not necessary.

2021-10-07 22:37 UTC, lucasespinosa28 reviewed
added recommended code changes

2021-10-11 10:59 UTC, lucasespinosa28 reviewed
I add the callback and the fetch in the background

the UI was improved

![Screenshot from 2021-10-11 02-44-22](https://user-images.githubusercontent.com/52639395/136779383-3de47879-3352-47cd-ae04-8bd458fb5703.png)
![Screenshot from 2021-10-11 02-52-00](https://user-images.githubusercontent.com/52639395/136779387-3b33a72c-00f4-419f-b16c-b70c4f46c74d.png)
![Screenshot from 2021-10-11 02-54-08](https://user-images.githubusercontent.com/52639395/136779389-64830092-62af-4d34-908d-eff9a21a18c7.png)
![Screenshot from 2021-10-11 03-29-16](https://user-images.githubusercontent.com/52639395/136779393-f5cf165d-44f5-45f1-a27f-7bfaab6a56b3.png)
![Screenshot from 2021-10-11 03-58-31](https://user-images.githubusercontent.com/52639395/136779395-e6d2773c-3fc8-4939-8c30-12bc35578bae.png)
![Screenshot from 2021-10-11 03-59-00](https://user-images.githubusercontent.com/52639395/136779397-9c763fa9-cc10-41b8-9038-303274398221.png)

2021-10-12 19:49 UTC, lucasespinosa28 reviewed
review

2021-10-13 01:46 UTC, lucasespinosa28 reviewed
problem loading images , solved

2021-10-13 09:55 UTC, lucasespinosa28 reviewed
misspelled name

2021-10-14 10:19 UTC, Jack-Works requested changes
I noticed you have changed some file permissions from 100644 to 100755. Please revert that, thanks

2021-10-14 14:23 UTC, lucasespinosa28 reviewed
the issue with files changed to 100644 to 100755 has been fixed

2021-10-20 06:20 UTC, lucasespinosa28 reviewed
I fixed the countdown and the error with texts

2021-10-20 07:06 UTC, lucasespinosa28 reviewed
refactor countdown

2021-10-25 00:01 UTC, lucasespinosa28 reviewed
I fixed the conflicts

2021-10-29 06:30 UTC, lucasespinosa28 reviewed
sorry for the delay,i fixed the big conflict

2021-10-29 15:42 UTC, lucasespinosa28 reviewed
fix conflict

2021-11-01 11:11 UTC, lucasespinosa28 reviewed
I fixed the plugin path

2021-11-10 15:21 UTC, guanbinrui commented on packages/mask/src/plugins/Foundation/SNSAdaptor/FoundationCountdown.tsx
> +                console.log(currentCount)
```suggestion
```

2021-11-10 15:31 UTC, guanbinrui commented on packages/mask/src/plugins/Foundation/SNSAdaptor/FoundationCountdown.tsx
> +    }, [currentCount])
```suggestion
    }, [currentCount, nftDateEnding])
```

2021-11-10 15:31 UTC, guanbinrui commented on packages/mask/src/plugins/Foundation/SNSAdaptor/FoundationHeader.tsx
> +    }, [])
```suggestion
    }, [props.nft.mostRecentAuction])
```

2021-11-10 15:31 UTC, guanbinrui commented on packages/mask/src/plugins/Foundation/SNSAdaptor/FoundationProvenances.tsx
> +    })
Sorting an array is a side-effect. Therefore, please create a duplication before sorting it.

2021-11-10 15:31 UTC, guanbinrui commented on packages/mask/src/plugins/Foundation/hooks/usePlaceBidCallback.ts
> +    const PlaceBidCallback = useCallback(async () => {
```suggestion
    const placeBidCallback = useCallback(async () => {
```

2021-11-11 05:20 UTC, AinuX commented
@lucasespinosa28

2021-11-12 21:39 UTC, lucasespinosa28 commented
> @lucasespinosa28
> 
> Could you share info how to access the testnet of Foundation (https://goerli.foundation.app/)? I have no idea where to apply the visitor password? thanks !

hi @AinuX, how to test foundation in goerli

1. access the foundation NFT contract in: https://goerli.etherscan.io/address/0x44458837ac4036337e5ce46ce28a744e05e02016#writeProxyContract
2. mint a new NFT and approve to use in the market, use this metadata already store in foundation IPFS, QmaT5krJGYkj6pkBt5GuMRDzZoFF2oThd9JZ9yxXwi4hec/metadata.js
![Captura de tela 2021-11-12 170644 (2)](https://user-images.githubusercontent.com/52639395/141537142-c904cadd-17bb-4189-b403-3b3c988a8433.png)
3. now add the NFT you minted to auction in the market,https://goerli.etherscan.io/address/0xeb1bd095061bbdb1ad065524628812cae63e4222#writeProxyContract
![Captura de tela 2021-11-12 171147 (2)](https://user-images.githubusercontent.com/52639395/141537384-f01afd09-cbb1-4d9d-81cb-2a9bbdfdb0a9.png)
4. in Twitter writer this, https://gorli.foundation.app/@testing/test- {id of NFT did you put to auction}
![Captura de tela 2021-11-12 171352 (2)](https://user-images.githubusercontent.com/52639395/141537598-6f695fce-3dbe-49e7-8c3b-a9731665689a.png)

2021-11-12 21:40 UTC, lucasespinosa28 reviewed
added format address and test in gorli

2021-11-15 03:36 UTC, wenluomask commented
Thanks for your quick reply and detailed instruction! Could you please rebuild your pr since the latest build is failed?

2021-11-15 21:58 UTC, lucasespinosa28 reviewed
@wenluomask , the build error was fixed

2021-11-16 07:26 UTC, AinuX commented
@lucasespinosa28 
Found some issues here, please take a look, thanks!

1. Style issue
![image](https://user-images.githubusercontent.com/2582974/141939733-56f40f4b-0699-4950-a0cc-b5e66bb53c35.png)

2. Fail to display if the NFT is stream media(like mp4, etc.)
![image](https://user-images.githubusercontent.com/2582974/141939780-17b0966f-3dd1-4e61-a7ab-8965e567102a.png)

2021-11-16 09:13 UTC, AinuX commented
@lucasespinosa28 
Since the current UI implementation is a bit different from our Collectibles plugin,  please refer to our figma to do some adjustments, thanks!
figma link: https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/TwitterV1?node-id=8896%3A0

2021-11-20 22:51 UTC, lucasespinosa28 reviewed
@AinuX, I recreate the UI using the refer from Figma, I did some changes  because of the limitation of foundation API and material UI 

the problem of not showing mp4 NFT only happen in testnet because the foundation does not have a video thumbnail for test NFT, in mainnet doesn't have this problem

https://twitter.com/search?q=%20%20%40withFND&src=typed_query&f=top
use this link to test the UI in mainnet
use the testnet version to test buy the NFT

https://user-images.githubusercontent.com/52639395/142742772-fd05a984-461b-434d-8f8e-4dce1d8ce9fb.mp4

2021-11-24 14:37 UTC, lucasespinosa28 reviewed
resolved conflict

2021-12-02 06:08 UTC, lucasespinosa28 reviewed
I fix the conflicts

2021-12-03 16:23 UTC, lucasespinosa28 reviewed
fix spell and media query

2021-12-07 06:27 UTC, lucasespinosa28 reviewed
fix conflict

2021-12-13 03:52 UTC, lucasespinosa28 reviewed
conflict fixed

2021-12-13 20:49 UTC, lucasespinosa28 reviewed
fix parseURL path

2021-12-14 02:25 UTC, lucasespinosa28 reviewed
conflict fixed

2021-12-28 21:47 UTC, lucasespinosa28 reviewed
conflict fixed

2022-01-08 03:16 UTC, lucasespinosa28 reviewed
fixed register plugins

2022-01-11 00:34 UTC, lucasespinosa28 reviewed
fixed problem with foundation

2022-01-11 01:17 UTC, lucasespinosa28 reviewed
fixed eslint errors

2022-01-25 19:54 UTC, lucasespinosa28 reviewed
eslint errors fixed

2022-03-22 02:56 UTC, LindaMask commented
@lucasespinosa28 hey are you on telegram or discord? can you reach out to me? Telegram:@lin_dao Discord:lin_DAO_#6015

2022-03-23 08:10 UTC, guanbinrui commented on packages/mask/src/plugins/Foundation/utils.ts
> +    const date = new Date(Number.parseInt(unix, 10) * 1000)
Recommend to use `date-fns`.

2022-03-23 08:19 UTC, septs commented on packages/mask/src/plugins/Foundation/SNSAdaptor/FoundationPlaceBid.tsx
> +    const testNet = chainId === 5
```suggestion
    const testNet = chainId === ChainId.Gorli
```

2022-04-08 02:08 UTC, septs commented on packages/mask/src/plugins/Foundation/SNSAdaptor/FoundationImage.tsx
> +    const is3D = src?.match(/\.(glb|gltf)$/i)
```suggestion
    const isModel = src?.match(/\.(glb|gltf)$/i)
```

2022-04-08 02:09 UTC, septs commented on packages/mask/src/plugins/Foundation/SNSAdaptor/FoundationImage.tsx
> +    const src = `${props.nftContract.baseURI}${image.at(-2)}/${image.at(-1)}`
plz use https://npm.im/urlcat build the url

2022-08-10 01:31 UTC, closed without merging