fix: dashboard style
DimensionDev/Maskbook pull request #4801
Opened 2021-11-11 08:28 UTC by NikoManiac

closes #

2021-11-24 05:24 UTC, wenluomask commented
Checked.

2021-11-25 03:26 UTC, Jack-Works requested changes

2021-11-25 03:26 UTC, Jack-Works commented on package.json
> +    "@dimensiondev/holoflows-kit": "^0.9.0-20210902104757-7c3d0d0",
Revert this change

2021-11-25 05:37 UTC, BillySh1 commented on package.json
> +    "@dimensiondev/holoflows-kit": "^0.9.0-20210902104757-7c3d0d0",
done

2021-11-25 07:33 UTC, guanbinrui approved these changes

2021-11-25 07:36 UTC, merged