chore: web3 context related
DimensionDev/Maskbook pull request #4840
Opened 2021-11-18 07:34 UTC by zhouhanseng

closes #

2021-11-18 08:35 UTC, zhouhanseng commented on packages/plugin-infra/src/web3/Context.tsx
> -export const usePluginsWeb3StateContext = PluginsWeb3StateContext.useContainer
`usePluginsWeb3State()` functions the same as `usePluginsWeb3StateContext()`

2021-11-18 08:39 UTC, zhouhanseng commented on packages/plugin-infra/src/web3/Context.tsx
> +export function usePluginWeb3Context(expectedPluginID?: string) {
`usePluginWeb3Context()` functions this same as `useWeb3State()`, but more readable.

2021-11-18 08:40 UTC, zhouhanseng commented on packages/plugin-infra/src/web3/useWeb3State.ts
> -export function useWeb3State(expectedPluginID?: string) {
There's a vague meaning between `useWeb3State()` and `usePluginWeb3StateContext()`

2021-11-25 03:48 UTC, Jack-Works requested changes

2021-11-25 03:48 UTC, Jack-Works commented on packages/shared-base/src/utils/compose.ts
> +export function compose(init: React.ReactNode, ...f: ((children: React.ReactNode) => JSX.Element)[]) {
This MUST NOT be in the shared-base package because it imports React. Please move it to `shared` package.

2021-11-25 03:48 UTC, Jack-Works commented on packages/plugins/Flow/src/hooks/useFCL.ts
> +    return useMemo(() => {
You should use `useRef`

2021-11-25 03:48 UTC, Jack-Works commented on packages/shared-base/src/utils/compose.ts
> +    return f.reduceRight((prev, curr) => curr(prev), React.createElement('div', '', init))
Your version is different than the original version. The original version creates a Fragment instead of a div.

2021-12-13 08:22 UTC, closed without merging