feat: labs
DimensionDev/Maskbook pull request #4899
Opened 2021-11-23 09:26 UTC by yanzhihong23

closes #

2021-11-23 10:16 UTC, guanbinrui commented on packages/dashboard/src/pages/Labs/constants.ts
> +export const TUTORIAL_URLS_EN: TUTORIAL_URLS_OPT = {
Suppose you need this configuration to update on the fly. Would you please take a look at https://github.com/DimensionDev/Maskbook-Configuration?

2021-11-23 10:17 UTC, guanbinrui submitted a review, later dismissed

2021-11-25 03:30 UTC, Jack-Works requested changes

2021-11-25 03:30 UTC, Jack-Works commented on packages/mask/.webpack/config.ts
> +                { test: /\.svg$/, use: ['@svgr/webpack'] },
Please do not add this.

2021-11-25 06:22 UTC, guanbinrui commented on packages/dashboard/src/pages/Labs/index.tsx
> +            window.open(url)
```suggestion
            window.open(url, '_blank', 'noopener noreferrer')
```

2021-11-25 15:16 UTC, Jack-Works approved these changes

2021-11-29 15:30 UTC, Jack-Works submitted a review, later dismissed

2021-12-02 07:33 UTC, wenluomask commented
1. Change Maskbox‘s link to https://realmasknetwork.notion.site/How-to-participate-in-a-MaskBox-sale-d0941687649a4ef7a38d71f23ecbe4da 
2. dHEDGE's link change to https://realmasknetwork.notion.site/Invest-in-your-favourite-fund-manager-via-dHEDGE-on-Twitter-ETH-and-Polygon-fb00ff2e626949279c83b59ed9207b9a
3. Add a full stop in Maskbox;
<img width="486" alt="Screen Shot 2021-12-02 at 3 17 16 PM" src="https://user-images.githubusercontent.com/85149605/144377320-42f4ea44-88dc-40c7-a02e-0160e5628239.png">

2021-12-02 07:37 UTC, yanzhihong23 commented
> 

updated

2021-12-02 07:57 UTC, wenluomask commented
Checked.

2021-12-02 08:16 UTC, guanbinrui approved these changes

2021-12-02 08:21 UTC, NikoManiac approved these changes

2021-12-02 08:21 UTC, merged