feat: add openocean
DimensionDev/Maskbook pull request #5198
Opened 2021-12-15 11:05 UTC by cformcn

closes #

2021-12-15 11:57 UTC, guanbinrui commented on packages/mask/src/plugins/Trader/apis/openocean/index.ts
> +    const _fromAmount = new BigNumber(request.fromAmount).dividedBy(pow10(request.fromToken.decimals ?? 0)).toNumber()
Using JS numbers for big integers will lead to overflow.

```suggestion
    const _resAmount = shiftLeft(outAmount, request.toToken.decimals).toFixed(),
    const _fromAmount = shiftLeft(request.fromAmount, request.fromToken.decimals).toFixed(),
```

2021-12-15 11:59 UTC, guanbinrui commented on packages/mask/src/plugins/Trader/apis/openocean/index.ts
> +    } as SwapOOData
`async function swapOO(request: SwapOORequest): SwapOOData { `

2021-12-15 12:00 UTC, guanbinrui commented on packages/mask/src/plugins/Trader/constants/openocean.ts
> +export const networkNames: Record<NetworkType, string> = {
We have a helper for this. Refer to `packages/web3-shared/evm/utils/enum.ts`.

2021-12-16 03:38 UTC, guanbinrui commented on packages/mask/src/plugins/Trader/apis/openocean/index.ts
> +    // const _fromAmount = new BigNumber(request.fromAmount).dividedBy(pow10(request.fromToken.decimals ?? 0)).toNumber()
```suggestion
    const { data, outAmount, minOutAmount, to, value } = payload
```

2021-12-20 04:11 UTC, septs requested changes
plz use https://aka.pw/svgomg reduce svg images

2021-12-20 06:05 UTC, Jack-Works commented on packages/mask/src/resources/OpenOceanIcon.tsx
> +        <desc>Created with Sketch.</desc>
Please cleanup those properties.

2021-12-27 06:06 UTC, wenluomask commented
1. Missing Unlock token button in BSC and Polygon. networks except for ETH. I tried to swap MASK->BNB, in this case the unlock button should show up;
<img width="697" alt="Screen Shot 2021-12-27 at 11 58 40 AM" src="https://user-images.githubusercontent.com/85149605/147432948-cb1ea699-979a-4af1-98cf-3af72bbd59bd.png">
<img width="632" alt="Screen Shot 2021-12-27 at 12 01 12 PM" src="https://user-images.githubusercontent.com/85149605/147433046-5ab141de-4738-4599-b72d-fb35fac5b553.png">

2. For the network didn't connected, OpenOcean DEX option should be show up as well. For example, if network is Polygon, I cannot find OpenOcean in DEX list unless I change to BSC;
<img width="684" alt="Screen Shot 2021-12-27 at 1 09 26 PM" src="https://user-images.githubusercontent.com/85149605/147436734-de5d9964-ae91-4daf-a84f-28ce89695059.png">

3. Each DEX needs to have estimate gas fee and show in DEX car since the best option is chosen by MAX($(minReceived)-$(estimate gas fee)). OpenOcean doesn't have estimate gas fee for networks except for ETH;
<img width="686" alt="Screen Shot 2021-12-27 at 1 06 36 PM" src="https://user-images.githubusercontent.com/85149605/147436756-b3ad4024-23f6-4e26-96d2-56b46be9923f.png">

2021-12-30 06:25 UTC, zhouhanseng commented
@wenluomask Fixed.

2021-12-30 07:52 UTC, wenluomask commented
#1 was not fixed yet.

2021-12-31 03:13 UTC, zhouhanseng commented
fixed

2021-12-31 03:37 UTC, wenluomask commented
Checked.

2021-12-31 10:53 UTC, merged