refactor: profile nft avatar
DimensionDev/Maskbook pull request #5248
Opened 2021-12-20 17:14 UTC by nuanyang233

closes MASK-461

2021-12-21 09:25 UTC, septs commented on packages/mask/src/social-network-adaptor/twitter.com/injection/NFT/NFTAvatarInTwitter.tsx
> +            return Number(style.width.replace('px', '') ?? 0)
plz do not use `Number` constructor.

use `Number.parseInt` replace it

2021-12-21 10:00 UTC, UncleBill requested changes

2021-12-21 12:24 UTC, nuanyang233 commented on packages/mask/src/social-network-adaptor/twitter.com/injection/NFT/NFTAvatarInTwitter.tsx
> +            return Number(style.width.replace('px', '') ?? 0)
https://stackoverflow.com/questions/24672309/methods-for-element-width-height/24757696

2021-12-21 14:33 UTC, guanbinrui approved these changes

2021-12-22 03:03 UTC, NikoManiac approved these changes

2021-12-22 03:04 UTC, merged