feat: link depends on provider
DimensionDev/Maskbook pull request #5405
Opened 2022-01-06 09:57 UTC by BillySh1

## Description

Closes # (NO_ISSUE)

## Type of change

- [ ] Documentation
- [x] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Previews

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

2022-01-06 10:43 UTC, septs requested changes

2022-01-06 10:43 UTC, septs commented on packages/mask/src/plugins/Collectible/pipes/index.ts
> +        [ChainId.Rinkeby]: 'https://rinkeby.rarible.com/',
```suggestion
        [ChainId.Rinkeby]: 'https://rinkeby.rarible.com',
```

2022-01-06 10:43 UTC, septs commented on packages/mask/src/plugins/Collectible/pipes/index.ts
> +                resolveLinkOnOpenSea(chainId === ChainId.Mainnet ? ChainId.Mainnet : ChainId.Rinkeby),
plz extract chain id computed result as variable to this function top-level

```suggestion
                resolveLinkOnOpenSea(computedChainId),
```

2022-01-07 08:21 UTC, orange187 commented
Checked

2022-01-07 08:25 UTC, septs commented on packages/mask/src/plugins/Collectible/pipes/index.ts
> +                    chainId === ChainId.Mainnet
plz extract this expression as variable.

2022-01-09 03:20 UTC, guanbinrui commented on packages/mask/src/plugins/Collectible/pipes/index.ts
> +export function resolveRaribleUserNetwork(chainId: ChainId) {
Refactor `createLookupTableResolver` to receive optional map.

```
export function createLookupTableResolver<K extends keyof any, T>(map: Partial<Record<K, T>,> fallback: T | ((key: K) => T)) {
    function resolveFallback(key: K) {
        if (typeof fallback === 'function') return (fallback as (key: K) => T)(key)
        return fallback
    }
    return (key: K) => map[key] ?? resolveFallback(key)
}


```

2022-01-09 03:21 UTC, guanbinrui commented on packages/mask/src/plugins/Collectible/SNSAdaptor/TokenTab.tsx
> +    console.log(asset.value, 'fff')
```suggestion
```

2022-01-09 03:23 UTC, guanbinrui commented on packages/mask/src/plugins/Collectible/SNSAdaptor/Collectible.tsx
> +                        (_asset.collectionLinkUrl && (
Make a component for this just like: packages/mask/src/plugins/Trader/SNSAdaptor/trending/Linking.tsx.

2022-01-09 03:24 UTC, guanbinrui commented on packages/mask/src/plugins/Collectible/SNSAdaptor/CheckoutDialog.tsx
> +                            <CheckoutOrder />
Are you sure to do this?

2022-01-09 06:46 UTC, septs commented on packages/mask/src/plugins/Collectible/pipes/index.ts
> +            return urlcat(resolveLinkOnRarible(chainId), `/token/${address}:${id}`)
```suggestion
        case NonFungibleAssetProvider.OPENSEA:
            return urlcat(resolveLinkOnOpenSea(chainId), ‘/assets/:address/:id', { address, id })
        case NonFungibleAssetProvider.RARIBLE:
            return urlcat(resolveLinkOnRarible(chainId), '/token/:address/:id', { address, id })
```

2022-01-11 01:59 UTC, guanbinrui approved these changes, later dismissed

2022-01-11 02:16 UTC, septs commented on packages/mask/src/plugins/Collectible/SNSAdaptor/CheckoutDialog.tsx
> +                            <CheckoutOrder />
?

2022-01-11 02:18 UTC, septs commented on packages/mask/src/plugins/Collectible/SNSAdaptor/LinkingAvatar.tsx
> +        )
```suggestion
        const url = new URL(href).toString()
        return (
            <Link href={url} title={title} target="_blank" rel="noopener noreferrer">
                <Avatar src={src} />
            </Link>
        )
```

2022-01-11 05:07 UTC, BillySh1 commented on packages/mask/src/plugins/Collectible/pipes/index.ts
> +        [ChainId.Rinkeby]: 'https://rinkeby.rarible.com/',
done

2022-01-11 05:07 UTC, BillySh1 commented on packages/mask/src/plugins/Collectible/pipes/index.ts
> +export function resolveRaribleUserNetwork(chainId: ChainId) {
done

2022-01-11 05:07 UTC, BillySh1 commented on packages/mask/src/plugins/Collectible/SNSAdaptor/CheckoutOrder.tsx
> +    const { token, asset, assetOrder, provider } = CollectibleState.useContainer()
Remove the props of CheckoutOrder because i get variables inside the component

2022-01-11 05:36 UTC, guanbinrui approved these changes

2022-01-11 05:36 UTC, merged