fix: icon style
DimensionDev/Maskbook pull request #5592
Opened 2022-01-30 05:40 UTC by Randolph314

## Description

Closes  [#MASK 667](https://mask.atlassian.net/browse/MASK-667)

## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Previews

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

2022-01-30 07:01 UTC, UncleBill approved these changes, later dismissed

2022-01-30 08:24 UTC, guanbinrui commented on pnpm-lock.yaml
> +    resolution: {integrity: sha512-vwArB0lTTuInOWTh5KeeNeJTswrGJrHebau8sdrG8TBNiVwAAehthfWflieMRKK54D11Z+7TO8fupCMa7BaoxA==}
Do not change this file without touch package.json.

2022-02-07 07:22 UTC, Jack-Works approved these changes, later dismissed

2022-02-08 09:08 UTC, septs requested changes
plz resolve conflict

2022-02-08 09:09 UTC, septs requested changes
plz use imageoptim reduce image resources

2022-02-08 13:43 UTC, Jack-Works commented
There is a merge conflict marker committed. Please revert that change.

2022-02-10 11:43 UTC, Jack-Works submitted a review, later dismissed

2022-02-15 08:54 UTC, wenluomask commented
Checked.

2022-02-15 11:20 UTC, yanzhihong23 approved these changes

2022-02-16 03:11 UTC, NikoManiac approved these changes

2022-02-16 03:24 UTC, Jack-Works approved these changes

2022-02-16 03:25 UTC, merged