feat(omen): plugin that integrates the decentralized prediction marke…
DimensionDev/Maskbook pull request #5844
Opened 2022-03-10 00:27 UTC by CriptKeeper

## Description

Closes # (3339)
Plugin that integrates the decentralized prediction market platform Omen.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Previews

### Swap View
![omen-view-swap](https://user-images.githubusercontent.com/99778032/157562438-44835433-24ef-49ef-b066-adbb3e8ebc33.png)

### Pool View
![omen-view-pool](https://user-images.githubusercontent.com/99778032/157562378-31f8221c-3a61-4235-af1b-0dfa84ab3bc7.png)

### History View
![omen-view-history](https://user-images.githubusercontent.com/99778032/157562458-919c10c8-eb61-4583-b01d-0dcc7156b476.png)

## Checklist

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
  - [x] I have removed all in development `console.log`s
  - [x] I have removed all commented code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

2022-03-24 02:34 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenDetailsCard.tsx
> +    const dailyVolume = Number(usdRunningDailyVolume).toPrecision(3)
Recommend to use `parseInt` or `parseFloat`.

2022-03-24 02:36 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenDetailsCard.tsx
> +        sharesAmount = tempSum.plus(nextVal)
Looks strange to me, only the last item of `liquidityArr` will take into account.

2022-03-24 02:36 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenDetailsCard.tsx
> +    let sharesAmount = new BigNumber(0)
```suggestion
    let sharesAmount = ZERO
```

2022-03-24 02:43 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenPoolView.tsx
> +// import { useRemoteControlledDialog } from '@masknet/shared'
```suggestion
```

2022-03-24 02:44 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenPoolView.tsx
> +
```suggestion
```

2022-03-24 02:44 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenPoolView.tsx
> +    const [inputAmount, setInputAmount] = useState<BigNumber>(new BigNumber(0))
```suggestion
    const [inputAmount, setInputAmount] = useState<BigNumber>(ZERO)
```

2022-03-24 02:44 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenPoolView.tsx
> +    const marketFee = props.marketFee ? new BigNumber(props.marketFee) : new BigNumber(0)
```suggestion
    const marketFee = props.marketFee ? new BigNumber(props.marketFee) : ZERO
```

2022-03-24 02:45 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/utils.ts
> +export function bigNumberToString(amount: BigNumber, decimals: number) {
Does `formatBalance` work for you?

2022-03-24 02:46 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/utils.ts
> +export function bigNumberToNumber(num: BigNumber | string, decimal = 8, fix = 8) {}
```suggestion
```

2022-03-24 02:47 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/utils.ts
> +BigNumber.config(normalConfig)
This behavior will change global settings. Please avoid doing this.

2022-03-24 02:48 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenPoolView.tsx
> +    // #endregion
For debugging?

2022-03-24 02:48 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenPoolView.tsx
> +                                        /* onClick={() => onPoolRequest('deposit')} */
```suggestion
```

2022-03-24 02:49 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenPoolView.tsx
> +                                        /* onClick={() => onPoolRequest('withdraw')} */
```suggestion
```

2022-03-24 02:49 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenSwapView.tsx
> +// import { useRemoteControlledDialog } from '@masknet/shared'
```suggestion
```

2022-03-24 02:49 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenSwapView.tsx
> +    // #endregion
For debugger?

2022-03-24 02:50 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenSwapView.tsx
> +                        /* onClick={() => onSwapRequest('buy')} */
```suggestion
```

2022-03-24 02:50 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenSwapView.tsx
> +                        /* onClick={() => onSwapRequest('sell')} */
```suggestion
```

2022-03-24 02:51 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/UI/OmenView.tsx
> +                closingTimestamp={new Date(1000 * +marketData.creationTimestamp)}
Recommend to use `fromUnixTime`.

2022-03-24 02:52 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/hooks/useHistory.ts
> +        return fetchHistory(id)
Recommend to use services RPC call.

2022-03-24 02:52 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/hooks/useMarket.ts
> +        return fetchMarket(id)
Recommend to use services RPC call.

2022-03-24 02:52 UTC, guanbinrui commented on packages/mask/src/plugins/Omen/hooks/useToken.ts
> +        return fetchToken(id)
Recommend to use services RPC call.

2022-03-24 11:11 UTC, septs requested changes

2022-03-24 11:11 UTC, septs commented on packages/mask/src/plugins/Omen/README.md
> +- <https://omen.eth.link/#/>
```suggestion
- <https://omen.eth.link>
```

2022-03-24 11:11 UTC, septs commented on packages/mask/src/plugins/Omen/README.md
> +Developed by @Dxdao\_ and powered by the Gnosis conditional tokens framework.
```suggestion
Developed by `@Dxdao_` and powered by the Gnosis conditional tokens framework.
```

2022-03-24 11:11 UTC, septs commented on packages/mask/src/plugins/Omen/README.md
> +- <>
```suggestion
- <https://github.com/DimensionDev/Maskbook/pull/5844>
```

2022-03-24 11:11 UTC, septs commented on packages/mask/src/plugins/Omen/SNSAdaptor/index.tsx
> +const isOmenURL = (link: string): boolean => regexLinkPattern.test(link)
```suggestion
const isOmenURL = (link: string) => regexLinkPattern.test(link)
```

2022-03-24 11:11 UTC, septs commented on packages/mask/src/plugins/Omen/UI/OmenDetailsCard.tsx
> +        sharesAmount = tempSum.plus(nextVal)
```suggestion
    const sharesAmount = BigNumber.sum(...Object.values(liquidityData).map((item) => item.sharesAmount))
```

2022-03-24 11:11 UTC, septs commented on packages/mask/src/plugins/Omen/UI/OmenDetailsCard.tsx
> +    const totalVolume = new BigNumber(collateralVolume).shiftedBy(collateralDecimals).toNumber().toPrecision(4)
```suggestion
    const liquidityAmount = sharesAmount.shiftedBy(collateralDecimals).toPrecision(4)
    const totalVolume = collateralVolume.shiftedBy(collateralDecimals).toPrecision(4)
```

2022-03-24 11:11 UTC, septs commented on packages/mask/src/plugins/Omen/UI/OmenHistoryView.tsx
> +                                                    .toPrecision(2)}
```suggestion
                                                {row.sharesOrPoolTokenAmount.shiftedBy(collateralDecimals).toPrecision(2)}
```

2022-03-24 11:11 UTC, septs commented on packages/mask/src/plugins/Omen/UI/OmenHistoryView.tsx
> +                                                    .toPrecision(2)}{' '}
```suggestion
                                                {row.collateralTokenAmount.shiftedBy(collateralDecimals).toPrecision(2)}{' '}
```

2022-03-24 11:11 UTC, septs commented on packages/mask/src/plugins/Omen/UI/OmenHistoryView.tsx
> +                                                {new Date(keys[index]).toDateString()}
@guanbinrui @Jack-Works suggest, update documentation specify date-time format method

e.g:
```js
import formatDateTime from "date-fns/format"

{formatDateTime(input, 'yyyy-MM-dd')}
```

2022-03-24 11:11 UTC, septs commented on packages/mask/src/plugins/Omen/UI/OmenPoolView.tsx
> +        fontWeight: theme.typography.fontWeightRegular as any,
plz do not use `any` type.

2022-03-24 11:11 UTC, septs commented on packages/mask/src/plugins/Omen/apis/index.ts
> +        Date.now() - marketLiquidityLastCachedAt > 30 * 1000
plz use https://date-fns.org/v2.28.0/docs/isBefore

2022-03-24 11:11 UTC, septs commented on packages/mask/src/plugins/Omen/apis/index.ts
> +    cachedMarketDetails = (await response.json())?.data
plz use https://github.com/DimensionDev/kit/blob/master/src/ecmascript/memoizePromise.ts

```ts
import { memoizePromise } from "@dimensiondev/kit"
```

2022-04-02 02:20 UTC, UncleBill commented
Hi @CriptKeeper , the branch behind the main branch a lot, please sync with it. Do not mix in so much commits from the main branch.

2022-04-08 01:04 UTC, septs commented on packages/mask/src/plugins/Omen/UI/OmenPoolView.tsx
> +                                        href={`${OMEN_BASE_URL}${marketId}/pool`}
plz use https://npm.im/urlcat build the url

2022-04-08 01:04 UTC, septs commented on packages/mask/src/plugins/Omen/UI/OmenPoolView.tsx
> +                                        href={`${OMEN_BASE_URL}${marketId}/pool`}
plz use https://npm.im/urlcat build the url

2022-04-08 01:04 UTC, septs commented on packages/mask/src/plugins/Omen/UI/OmenPoolView.tsx
> +// // Total Liquidity
plz remove all comments.

2022-04-08 01:05 UTC, septs commented on packages/mask/src/plugins/Omen/UI/OmenSwapView.tsx
> +                        href={`${OMEN_BASE_URL}${marketId}/buy`}
plz use https://npm.im/urlcat build the url

2022-04-08 01:05 UTC, septs commented on packages/mask/src/plugins/Omen/UI/OmenSwapView.tsx
> +                        href={`${OMEN_BASE_URL}${marketId}/sell`}
plz use https://npm.im/urlcat build the url

2022-08-10 01:31 UTC, closed without merging