fix: api parameters
DimensionDev/Maskbook pull request #5905
Opened 2022-03-18 05:51 UTC by guanbinrui

## Description

Closes # (NO_ISSUE)

## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

2022-03-22 03:45 UTC, guanbinrui commented
@DimensionDev/qa

2022-03-23 10:06 UTC, Jack-Works requested changes

2022-03-23 10:06 UTC, Jack-Works commented on packages/dashboard/src/index.tsx
> -    <StrictMode>
Reason?

2022-03-23 10:06 UTC, Jack-Works commented on packages/shared-base/src/Pure/index.ts
> +export const NOOP = Object.freeze(() => {})
use `noop` from lodash.

2022-03-23 10:06 UTC, Jack-Works commented on cspell.json
> -        "destory",
I suggest you to open another PR for this correction.

2022-03-25 08:34 UTC, Jack-Works approved these changes, later dismissed

2022-03-31 03:50 UTC, Jack-Works approved these changes

2022-08-10 01:31 UTC, closed without merging