feat: inject mask at reply
DimensionDev/Maskbook pull request #5911
Opened 2022-03-20 02:50 UTC by lelenei

## Description

Closes # (NO_ISSUE)

## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Previews

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

2022-03-22 03:40 UTC, Jack-Works requested changes

2022-03-22 03:40 UTC, Jack-Works commented on packages/mask/src/components/CompositionDialog/Composition.tsx
> +                        reply={reply}
Do not pass down this props to CompositionUI, but handle it in `onSubmit_`.

2022-03-22 12:25 UTC, guanbinrui commented on packages/shared-base/src/Messages/Mask.ts
> +    message: AutoPasteFailedEvent
Use a proper name. This one is vague.

2022-03-22 12:36 UTC, guanbinrui commented on packages/mask/src/social-network-adaptor/twitter.com/utils/selector.ts
> +    if (isReply()) {
Here it is detecting whether a reply editor is used with the current location. Does it go to mismatch if the composition modal is opening? Like the pic below, both two editors exist.

<img width="591" alt="image" src="https://user-images.githubusercontent.com/52657989/159483370-d1a8baaf-3b6b-47e3-832d-2651b3d6adaa.png">

2022-03-22 12:38 UTC, guanbinrui commented on packages/mask/src/social-network/types.ts
> +            reply?: boolean
Replying is only needed by Twitter. Please use a proper name if you need to change the option for all SNS.

2022-03-22 13:05 UTC, guanbinrui commented on packages/shared-base/src/Messages/Mask.ts
>      readonly reason: 'timeline' | 'popup'
Can you keep using the `reason` field?

2022-03-23 06:45 UTC, guanbinrui commented on packages/mask/src/social-network-adaptor/twitter.com/utils/selector.ts
> +    if (isReply()) {
@lelenei

2022-03-23 07:19 UTC, guanbinrui approved these changes

2022-03-23 07:19 UTC, guanbinrui commented
@DimensionDev/qa

2022-03-23 07:29 UTC, AinuX commented
Checked

2022-03-23 14:35 UTC, merged