Refactor/migrate evm
DimensionDev/Maskbook pull request #6002
Opened 2022-03-30 15:26 UTC by guanbinrui

## Description

Closes # (NO_ISSUE)

## Type of change

- [ ] Documentation
- [x] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

2022-03-31 03:37 UTC, Jack-Works commented on packages/mask/src/extension/popups/pages/Wallet/ContractInteraction/index.tsx
> +import { EVM_RPC } from '@masknet/plugin-evm/src/messages'
you should not import from `src` or `dist` folder.

2022-04-07 06:32 UTC, Jack-Works commented on packages/plugins/EVM/package.json
> +    "web3": "1.5.2",
1.7.1

2022-04-07 06:39 UTC, Jack-Works commented on packages/web3-providers/src/mask/prepare.ts
> +if (typeof self !== 'undefined') {
hmm what are you doing? why you need a worker in this package?

2022-04-19 05:25 UTC, Jack-Works requested changes
pnpm:

>  WARN  There are cyclic workspace dependencies

TypeScript:

```
error TS6202: Project references may not form a circular graph. Cycle detected: tsconfig.json
packages/mask/tsconfig.json
packages/mask/src/tsconfig.json
packages/shared/tsconfig.json
packages/web3-shared/evm/tsconfig.json
packages/plugin-infra/tsconfig.json
packages/web3-providers/tsconfig.json
```

2022-04-19 05:25 UTC, Jack-Works commented on packages/shared-base/src/utils/subscription.ts
> +export function mergeSubscription<T>(...subs: Subscription<unknown>[]) {
This is not type-safe. Please change to the correct type signature.

2022-04-19 05:25 UTC, Jack-Works commented on packages/shared-base/src/ondemand-worker/index.ts
> +/**
You should delete another copy of this file in this project.

2022-04-19 05:25 UTC, Jack-Works commented on packages/shared-base/src/Site/index.ts
> +function getExtensionSiteType() {
Please try `getEnvironment` exported from the `'@dimensiondev/holoflows-kit'` package.

2022-04-19 05:25 UTC, Jack-Works commented on packages/shared-base/src/Settings/index.ts
> +import { defer } from '@dimensiondev/kit'
Please do not add new Settings API based on ValueRef.

Use `packages/shared-base/src/kv-storage`. You can find an example at `packages/mask/shared/kv-storage.ts`

2022-04-19 05:25 UTC, Jack-Works commented on packages/plugin-infra/src/types.ts
> +import type { EthereumTransactionConfig } from '../../web3-providers/node_modules/@masknet/web3-shared-evm'
Please do not import type like this.

2022-04-19 05:25 UTC, Jack-Works commented on packages/plugin-infra/src/types.ts
> +        hasNativeAPI: boolean
You do not need both. Only provide one.

2022-04-19 05:25 UTC, Jack-Works commented on packages/plugin-infra/src/types.ts
> +        nativeSendJsonString?: (message: string) => Promise<string>
Why expose this to the plugin?

2022-04-19 05:25 UTC, Jack-Works commented on packages/mask/src/plugins/Collectible/SNSAdaptor/MakeOfferDialog.tsx
> +import type { useAsset } from '@masknet/plugin-evm/src/hooks'
Please do not import from `src/`

2022-04-19 05:25 UTC, Jack-Works commented on packages/mask/src/plugins/Collectible/apis/openseaFromSDK.ts
> +import { EVM_RPC } from '@masknet/plugin-evm/src/messages'
Please do not import from `src/`

2022-05-11 16:31 UTC, Jack-Works commented
![image](https://user-images.githubusercontent.com/5390719/167901061-f447f20c-235c-4fb1-a56d-d55b9328069c.png)

This PR is horrifying big, is it possible to split it into multiple PRs?

2022-05-14 05:09 UTC, septs commented on packages/plugin-infra/src/web3-state/Provider.ts
> +        if (needToUpdateProviderType) {
```suggestion
        if (!needToUpdateProviderType) return
```

2022-05-27 02:50 UTC, merged