chore: add failed checklist
DimensionDev/Maskbook pull request #6220
Opened 2022-05-09 10:51 UTC by septs

## Description

Closes # (NO_ISSUE)

## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Previews

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

2022-05-10 02:29 UTC, Jack-Works requested changes

2022-05-10 02:29 UTC, Jack-Works commented on docs/failed-checklist.md
> +# Failed Checklist
Build failure / Runtime crash checklist

2022-05-10 02:29 UTC, Jack-Works commented on docs/failed-checklist.md
> +1. Run `gulp clean`, Cleanup Caching
```suggestion
1. Run `npx gulp clean`, Cleanup cache and built files
```

2022-05-10 02:29 UTC, Jack-Works commented on docs/failed-checklist.md
> +## Install failed
CI Error: Cannot connect to git@github.com, public key rejected

2022-05-10 02:29 UTC, Jack-Works commented on docs/failed-checklist.md
> +1. Run `gulp fix-lockfile`, Rebuild lockfile
```suggestion
1. Run `npx gulp fix-lockfile`
```

2022-05-10 03:14 UTC, Jack-Works commented on docs/failed-checklist.md
> +## Build failed
actually this command also works for runtime crash

2022-05-10 03:47 UTC, Jack-Works commented on docs/failed-checklist.md
> +## Runtime crash
```suggestion
# Checklist

## Build error / Runtime crash
```

2022-05-10 03:47 UTC, Jack-Works submitted a review, later dismissed

2022-05-11 06:19 UTC, guanbinrui approved these changes, later dismissed

2022-05-11 06:19 UTC, guanbinrui commented on docs/failed-checklist.md
> +1. Run `npx gulp clean`, Cleanup cache and built files
build files.

2022-05-11 06:26 UTC, septs commented on docs/failed-checklist.md
> +1. Run `npx gulp clean`, Cleanup cache and built files
```suggestion
1. Run `npx gulp clean`, Cleanup cache and build files
```

2022-05-11 07:22 UTC, Jack-Works approved these changes

2022-05-11 07:23 UTC, merged