feat: add NextID in profile db when select & no localkey err improve
DimensionDev/Maskbook pull request #6348
Opened 2022-05-25 19:03 UTC by BillySh1

## Description

Closes #MF-811 MF-826

## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Previews

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

2022-05-26 00:47 UTC, septs commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipients.tsx
> +                7823
？

2022-05-26 07:50 UTC, Jack-Works commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipients.tsx
> +import type { ProfileRecord } from '../../../../background/database/persona/type'
Please do not use this type. It is marked as internal (only can be used in the background). If you need to modify the profile, please use another representation.

2022-05-26 07:53 UTC, Jack-Works requested changes

2022-05-26 07:53 UTC, Jack-Works commented on packages/mask/background/services/crypto/recipients.ts
> +}
Please do not add it here. You should add a "recipient" like a normal persona-profile link.

It should be located in `packages\mask\background\services\identity\`. (And you maybe don't need to add a new method. Please try to use existing method.)

2022-06-27 13:17 UTC, Jack-Works commented on packages/mask/background/services/identity/profile/update.ts
> +export async function attachNextIDTuProfileDB(item: ProfileInformationFromNextID) {
```suggestion
export async function attachNextIDToProfileDB(item: ProfileInformationFromNextID) {
```

2022-06-27 13:18 UTC, Jack-Works commented on packages/mask/background/services/identity/profile/update.ts
> +        identifier: item.linkedPersona!,
do not assert those fields. please check before use.

2022-06-27 13:18 UTC, Jack-Works commented on packages/mask/background/services/identity/profile/update.ts
> +        updatedAt: item.updatedAt!,
do not assert those fields. please check before use.

2022-06-27 13:19 UTC, Jack-Works commented on packages/mask/background/services/identity/profile/update.ts
> +export async function attachNextIDTuProfileDB(item: ProfileInformationFromNextID) {
or `attachNextIDPersonaToProfile`

2022-07-05 16:27 UTC, Jack-Works commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipients.tsx
> +        await Promise.all(
import `batch` from `async-call-rpc`. you can send multiple RPC requests at once.

```js
const [rpc, emit, drop] = batch(Services.Identity)
rpc.attachNextIDPersonaToProfile(...)
emit()
```

2022-07-05 16:29 UTC, Jack-Works commented on packages/mask/background/services/identity/profile/update.ts
> +    const personaRecord = {
```suggestion
    const personaRecord: PersonaRecordDB = {
```

Otherwise, you won't get type check in a good way.

2022-07-06 09:59 UTC, Jack-Works commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipients.tsx
> +import { batch } from 'async-call-rpc/base'
```suggestion
import { batch } from 'async-call-rpc'
```

2022-07-06 10:06 UTC, Jack-Works commented on packages/mask/background/services/identity/profile/update.ts
> +            await createProfileDB(profileRecord, t)
You should use createOrUpdateProfileDB if there is already an old one.

2022-07-06 10:31 UTC, Jack-Works submitted a review, later dismissed

2022-07-06 10:45 UTC, guanbinrui commented on packages/mask/background/services/identity/profile/update.ts
> +    }
```suggestion
    const now = new Date()
    const personaRecord: PersonaRecord = {
        createdAt: now,
        updatedAt: now,
        identifier: item.linkedPersona,
        linkedProfiles: new Map(),
        publicKey: await decompressSecp256k1Key(item.linkedPersona.rawPublicKey),
        publicHexKey: item.linkedPersona?.publicKeyAsHex,
        nickname: item.nickname,
        hasLogout: false,
        uninitialized: false,
    }

    const profileRecord: ProfileRecord = {
        identifier: item.identifier,
        nickname: item.nickname,
        linkedPersona: item.linkedPersona,
        createdAt: now,
        updatedAt: now,
    }
```

2022-07-06 10:51 UTC, merged