feat: create r2d2 fetch for web3 provider
DimensionDev/Maskbook pull request #6443
Opened 2022-06-08 06:03 UTC by Lanttcat

## Description

Closes # (NO_ISSUE)

## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Previews

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

2022-06-09 06:02 UTC, Jack-Works requested changes

2022-06-09 06:02 UTC, Jack-Works commented on packages/shared-base/src/serializer/response.ts
> +    return new TypesonPromise<{ binaryArray: Uint8Array[]; init: ResponseInit }>(async (resolve, reject) => {
```suggestion
    return new TypesonPromise<{ body: Uint8Array[]; init: ResponseInit }>(async (resolve, reject) => {
```

2022-06-09 06:02 UTC, Jack-Works commented on packages/shared-base/src/serializer/response.ts
> +                headers: { 'Content-Type': 'application/json' },
You should capture the original headers instead of hard-coded in JSON.

2022-06-09 06:02 UTC, Jack-Works commented on packages/shared-base/src/serializer/index.ts
> +import { is as responseIs, de as responseDe, ser as responseSer } from './response'
export `[is, ser, der]` from the response directly.

2022-06-09 06:02 UTC, Jack-Works commented on packages/shared-base/src/serializer/index.ts
> +        Response: [responseIs, responseSer, responseDe],
you need to also add support for `Request`.

2022-06-10 08:04 UTC, guanbinrui approved these changes

2022-06-10 08:04 UTC, merged