refactor: migration wallet plugin
DimensionDev/Maskbook pull request #8744
Opened 2023-02-20 06:38 UTC by guanbinrui

## Description

Closes # (NO_ISSUE)

## Type of change

- [ ] Documentation
- [x] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Previews

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

2023-02-24 02:36 UTC, guanbinrui commented on packages/plugins/Wallet/src/SNSAdaptor/PluginSelectProviderDialog/index.tsx
> +            misc_openCreateWalletView={nativeAPI?.api.misc_openCreateWalletView}
```suggestion
```

2023-02-24 02:37 UTC, guanbinrui commented on packages/plugins/Wallet/src/SNSAdaptor/DashboardSelectProviderDialog/index.tsx
> +            misc_openCreateWalletView={nativeAPI?.api.misc_openCreateWalletView}
```suggestion
```

2023-02-24 02:39 UTC, guanbinrui commented on packages/plugins/MaskBox/src/SNSAdaptor/components/PreviewCard.tsx
> +import { WalletConnectedBoundary, ChainBoundary } from '@masknet/plugin-wallet'
?

2023-02-24 02:41 UTC, guanbinrui commented on packages/plugins/MaskBox/src/SNSAdaptor/components/DrawDialog.tsx
> +import { GasSettingBar, PluginWalletStatusBar, WalletConnectedBoundary } from '@masknet/plugin-wallet'
`PluginWalletStatusBar` and `WalletConnectedBoundary` should stay in `@masket/shared`.

2023-02-27 09:59 UTC, Jack-Works requested changes

2023-02-27 09:59 UTC, Jack-Works commented on packages/plugins/Wallet/src/index.ts
> +export * from './SNSAdaptor/index.js'
Do not export JSX from this file. It might break some runtime that does not have DOM.

Add a new entry for this package instead.

2023-02-28 04:02 UTC, guanbinrui commented on packages/mask/src/plugins/NextID/SNSAdaptor/index.tsx
> +                <ApplicationBoardDialog />
?

2023-02-28 04:05 UTC, guanbinrui commented on packages/mask/src/plugins/NextID/components/BindPanelUI.tsx
> +import { WalletStatusBox } from '../../../../../plugins/Wallet/src/SNSAdaptor/Components/WalletStatusBox/index.js'
?

2023-05-18 22:10 UTC, closed without merging