fix: shared with ui
DimensionDev/Maskbook pull request #9650
Opened 2023-05-23 09:29 UTC by lelenei

## Description

Closes mf-4175

## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Previews

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

2023-05-23 10:05 UTC, Jack-Works requested changes

2023-05-23 10:05 UTC, Jack-Works commented on packages/mask/src/components/CompositionDialog/CompositionUI.tsx
> +    const persona = useCurrentPersona()
You should not call `useCurrentPersona()` in `CompositionDialogUI`. It must be a stateless component. Add it to the props list and call `useCurrentPersona` in `CompositionDialog`

2023-05-23 10:05 UTC, Jack-Works commented on packages/mask/src/components/CompositionDialog/CompositionUI.tsx
> +                <PersonaAction currentPersona={persona} classes={{ bottomFixed: classes.persona }} />
If `<PersonaAction>` is not pure, please remove it and use `{ props.PersonaAction }` and pass a JSX in the call site.

2023-05-23 10:05 UTC, Jack-Works commented on packages/mask/src/utils/utils.ts
> +        rpc.attachNextIDPersonaToProfile(newItem, whoAmI)
if you do not need the return value, you can also use `notify` from `async-call-rpc`. It will drop the return value.

2023-05-25 09:44 UTC, Jack-Works commented on packages/mask/src/utils/utils.ts
> +        rpc.attachNextIDPersonaToProfile(newItem, whoAmI)
notify and batch can be used together. if you need it to improve the performance.

2023-05-29 07:20 UTC, guanbinrui commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
> +        [results, props.items],
```suggestion
        [results],
```

2023-05-29 07:21 UTC, guanbinrui commented on packages/mask/src/components/CompositionDialog/Composition.tsx
> +                    personaAction={personaAction}
```suggestion
                    personaAction={persona ? (
        <PersonaAction currentPersona={persona} classes={{ bottomFixed: classes.persona }} />
    ) : null}
```

2023-05-29 07:21 UTC, guanbinrui commented on packages/mask/src/components/CompositionDialog/CompositionUI.tsx
> +    personaAction?: React.ReactNode
```suggestion
    PersonaAction?: React.ReactNode
```

2023-05-29 07:22 UTC, guanbinrui commented on packages/mask/src/components/CompositionDialog/CompositionUI.tsx
> +                <div className={classes.personaAction}>{props.personaAction}</div>
```suggestion
                {props.PersonaAction ? <div className={classes.personaAction}>{props.personaAction}</div> : null}
```

2023-05-29 07:23 UTC, guanbinrui commented on packages/mask/src/components/shared/SelectProfileUI/SelectProfileUI.tsx
> +    const onSelectedProfiles = useCallback(
```suggestion
    const onSelectProfile = useCallback(
```

2023-05-29 07:23 UTC, guanbinrui commented on packages/mask/src/components/shared/SelectProfileUI/SelectProfileUI.tsx
> +    const onSelectedAll = useCallback(
```suggestion
    const onSelectAll = useCallback(
```

2023-05-29 07:26 UTC, guanbinrui commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
> +    }, [])
```suggestion
    }, [item])
```

2023-05-29 15:20 UTC, lelenei commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
> +    }, [])
this doesn't need to be changed

2023-05-30 01:21 UTC, guanbinrui approved these changes

2023-05-30 01:21 UTC, guanbinrui submitted a review, later dismissed

2023-05-30 03:18 UTC, UncleBill commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
> +                                        </div>
Use the `<EmptyStatus />` component

2023-05-30 03:18 UTC, UncleBill commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
> +                setSelectedAllProfiles([])
Why creating a copy?

2023-05-30 03:18 UTC, UncleBill commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
> +        props.onSetSelected([...selectedAllProfiles])
Why creating a copy?

2023-05-30 03:18 UTC, UncleBill commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
> +            )
If none of the profiles gets modified (you should double check)
```suggestion
            setSelectedAllProfiles((profiles) =>
                profiles.filter((x) => x !== item),
            )
```

2023-06-01 03:36 UTC, UncleBill approved these changes, later dismissed

2023-06-01 03:48 UTC, guanbinrui commented on packages/mask/src/components/shared/SelectProfileUI/SelectProfileUI.tsx
> +        [items, selected],
```suggestion
        [items],
```

2023-06-01 03:57 UTC, guanbinrui commented on packages/mask/src/components/CompositionDialog/CompositionUI.tsx
> +                <div className={classes.personaAction}>{props.personaAction}</div>
For placeholder:

```tsx
{props.personaAction ?? <div className={classes.personaAction} />}
```

2023-06-01 04:14 UTC, guanbinrui submitted a review, later dismissed

2023-06-01 06:49 UTC, Jack-Works commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
> +                setSelectedAllProfiles([...results])
what's the difference if nothing has changed?

2023-06-01 06:50 UTC, Jack-Works commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
> +    const [selectedAllProfiles, setSelectedAllProfiles] = useState<Profile[]>(props.items)
```suggestion
    const [selectedAllProfiles, setSelectedAllProfiles] = useState<readonly Profile[]>(props.items)
```

2023-06-01 06:51 UTC, Jack-Works commented on packages/mask/src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
> +                setSelectedAllProfiles([...results])
i understand

2023-06-02 03:53 UTC, merged

2023-06-02 05:04 UTC, Jack-Works commented on packages/mask/src/utils/utils.ts
> +export async function attachNextIDToProfile(nextID: ProfileInformationFromNextID) {
hmmm this should be a new service in the background...