refactor: migrate TransactionSnackbar
DimensionDev/Maskbook pull request #9865
Opened 2023-06-18 07:50 UTC by lelenei

## Description

Closes mf-4345

## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Previews

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

2023-06-18 11:58 UTC, Jack-Works requested changes

2023-06-18 11:58 UTC, Jack-Works commented on packages/mask/src/plugins/Wallet/Dashboard/index.tsx
> +                {getSiteType() !== ExtensionSite.Popup ? TransactionSnackbar.open() : null}
this doesn't look right. open() looks like a side-effect function you should not call it in the render function. if open() does not have a side-effect, please rename that function.

2023-06-18 11:58 UTC, Jack-Works commented on packages/mask/src/plugins/Wallet/SNSAdaptor/index.tsx
> +                    TransactionSnackbar.open({ pluginID }),
this doesn't look right. open() looks like a side-effect function you should not call it in the render function. if open() does not have a side-effect, please rename that function.

2023-06-19 02:16 UTC, guanbinrui commented on pnpm-lock.yaml
> +    dev: true
Remove node_modules and run `pnpm install` again.

2023-06-20 03:07 UTC, guanbinrui commented on packages/shared/src/modals/TransactionSnackbar/index.tsx
> +            setPluginID(props?.pluginID)
```suggestion
            setPluginID(props.pluginID)
```

2023-06-20 03:08 UTC, guanbinrui approved these changes, later dismissed

2023-06-20 03:27 UTC, guanbinrui approved these changes

2023-06-20 03:28 UTC, merged