fix: component must be wrapper with <container.provider>
DimensionDev/Maskbook pull request #9981
Opened 2023-07-04 01:17 UTC by lelenei

## Description

Closes # (NO_ISSUE)

## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Previews

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

2023-07-04 02:12 UTC, UncleBill commented on packages/plugins/RSS3/src/SNSAdaptor/modals/DetailsModal/index.tsx
> +            </ScopedDomainsContainer.Provider>
If `FeedsPage` and `FeedDetailsDialog` are wrapped in individual components, we cannot guarantee consistent results between them!

2023-07-06 03:01 UTC, UncleBill requested changes

2023-07-06 03:01 UTC, UncleBill commented on packages/plugins/RSS3/src/SNSAdaptor/modals/DetailsModal/index.tsx
> +    map?: Record<string, string>
```suggestion
    scopedDomainsMap: Record<string, string>
```

It would be hard to guess what `map` is to FeedDetailsModal

2023-07-06 03:01 UTC, UncleBill commented on packages/plugins/RSS3/src/SNSAdaptor/modals/DetailsModal/index.tsx
> +                setScopedDomainMap(props?.map)
```suggestion
                setScopedDomainMap(props.map)
```

2023-07-06 07:04 UTC, guanbinrui approved these changes

2023-07-06 07:04 UTC, merged